### ISSUE TITLE
ShestakUI issue

### ISSUE THREAD

**Issue by AlbertDuval** [Wetxius/Numeration#1]
Hi Wetxius,

First, I'm sorry to ask you something about ShestakUI here, but it's seems it was the only way.
I'm new in GitHub and I try to fork ShestakUI, I try it straight in my WoW Interface/Addons/ directory. But there a sub folder ShestakUI, so it doesn't work with WoW.
I saw many other WoW addons like your Numeration without a sub folder, this layout make it possible to fork straight in WoW directory.
Do you have any idea, how can I fix this thing of sub folder for Shestak ?

Thank you in advance.
Best regards,
AlbertDuval

**Comment by Wetxius** [comment]
http://shestak.org/forum/showpost.php?p=5297&postcount=24
Maybe it helps.

**Comment by AlbertDuval** [comment]
It helps, thank you (and also Google translate)
Please continue, to make this really good job of updating ShestakUI, because it's one of the best WoW UI
