### ISSUE TITLE
Your bindings.xml is introducing taint (fix included)

### ISSUE THREAD

**Issue by tflo** [Wetxius/Numeration#11]
Your Category variable in bindings.xml produces taint.

To reproduce:

1. Reload game client _with all addons unloaded_, except Numeration.
2. Open the Blizzard Options (Settings) Panel.
3. In the sidebar, click on Keybindings. (Important)
4. Exit the Options Panel.
5. You should get the taint dialog box now. ("Numeration has been blocked…")
6. Do the same test without Numeration loaded, if you want.

Please see [this thread](https://us.forums.blizzard.com/en/wow/t/bindingsxml-taint-and-other-issues/1394681) for more info on the issue. You find a working solution in [post 9](https://us.forums.blizzard.com/en/wow/t/bindingsxml-taint-and-other-issues/1394681/9) of that thread. 

So, in your case a taint-free bindings.xml would be, for example:

```xml
<Bindings>
	<Binding category="Numeration " name="NUMERATION_VISIBILITY">
		Numeration:ToggleVisibility()
	</Binding>
	<Binding category="Numeration " name="NUMERATION_RESET">
		StaticPopup_Show("RESET_DATA")
	</Binding>
</Bindings>
```

The trailing space in the string is just to avoid that it resolves to a global of the same name you _might_ have somewhere.

– Tom

**Comment by Wetxius** [comment]
Thank you, implement https://github.com/Wetxius/Numeration/commit/907389a92bbcae0d3e167eeb64e143230d3bf508

**Comment by tflo** [comment]
Thanks for implementing.
