### ISSUE TITLE
Warning: Spell ID [Drowning] no longer exists

### ISSUE THREAD

**Issue by Zeraxxus** [Wetxius/Numeration#4]
Hi, first of all, thanks for this nifty and lightweight damage meter.

Now to my issue: During the mythic dungeon Shrine of the Storm, there was this "Drowned Depthbringer" NPC debuffing us with an ability called "Touch of the Drowned". I had my Numeration set to show damage from abilities so I could see what was going on, and for some reason this was causing issues during combat.

[Drowned Depthbringer](https://www.wowhead.com/npc=134418)
[Touch of the Drowned](https://www.wowhead.com/spell=268322)

![wowscrnshot_082018_224656](https://user-images.githubusercontent.com/948880/44372880-562ca580-a4e6-11e8-9e8d-852bd232016f.jpg)

**Comment by Wetxius** [comment]
Try https://github.com/Wetxius/Numeration/commit/20d366c203cd0df484f36e310832a1b1cee47a06
Should be fixed.

**Comment by Zeraxxus** [comment]
I played with the changes, and I didn't get any errors in chat this time. Cheers!
