### ISSUE TITLE
[suggestion] Total Healing + Absorb

### ISSUE THREAD

**Issue by tflo** [Wetxius/Numeration#5]
IMO, Numeration is nearly perfect as a lightweight damage meter.

Just a very tiny feature request: Adding a “Total Healing + Absorb” type (as in Skada).

Like this:

![numeration](https://user-images.githubusercontent.com/1410282/97790804-1e444100-1bcc-11eb-88e5-83534618c1bb.jpg)

You could comment it out by default, so it would change nothing for other users who don’t like it.

---

If you reject the suggestion, I have a question then:

As you see in the screenshot, I have already added that feature for me. But I’m not familiar neither with Lua nor with the API or the combat log. I have simply added a new event to the `collect.SPELL_HEAL` function in Collect.lua, after line 374:

``` 
      EVENT("hdt", srcGUID, dstName, spellId, amount, timestamp) -- line 375
```

(And of course added a new type for `hdt` + `ga` in Config.lua.)

The numbers I get seem correct, so far. But, maybe you can just tell me, if this is (more or less) the correct/economic way to implement it? If not, maybe a little hint…

– Tom

**Comment by Wetxius** [comment]
You can try add new category in config
```lua
	{	-- Healing + Absorb + Overhealing
		name = SHOW_COMBAT_HEALING.." + "..COMBAT_TEXT_ABSORB,
		id = "hd",
		id2 = "ga",
		id3 = "oh",
		c = {.25, .5, .85},
	},
```

**Comment by tflo** [comment]
Nope. `id3` is ignored:

![WoWScrnShot_110120_113819](https://user-images.githubusercontent.com/1410282/97800979-c3e1c980-1c39-11eb-9833-2ad667fc6c7f.jpg)

**Comment by Wetxius** [comment]
You can add new line after https://github.com/Wetxius/Numeration/blob/master/Collect.lua#L372
```lua
EVENT("hdt", srcGUID, dstName, spellId, overhealing)
```

**Comment by Wetxius** [comment]
So there is no simple method.

**Comment by tflo** [comment]
Well, then I’ll stick to my method. Thanks for the info, really appreciated.

Any plans to add it in a future release?

**Comment by Wetxius** [comment]
I see no point in watching overhealing and healing together. So answer is no.

**Comment by tflo** [comment]
The point is that the total healing is useful when evaluating talents/trinkets/essences etc., since it shows the healing _potential_ you get. What is overhealing in  one fight can be actual healing in the next one.

But obviously we can also get the total healing by adding up healing and overhealing. So it effectively saves some mental arithmetic :-)

Thanks anyway!
