### ISSUE TITLE
[UI flaw] Confirmation overkill for reset

### ISSUE THREAD

**Issue by tflo** [Wetxius/Numeration#7]
It’s obligatory to have a confirmation dialog  before resetting – if there is any risk that it could be a mis-click.
Mis-clicking may happen if Reset is selected from the drop-down menu, so, a confirmation there is ok and necessary.

But not so much when resetting via the MiniMap Icon: Here we already have to Shift-click. This is a very explicit action, and, opposed to a simple left-click, the risk of doing this accidentally is very low.

I propose to remove the confirmation when the icon is Shift-clicked. The act of holding down Shift is enough confirmation, IMO.

Even if you do not agree with the above, in any case the confirmation for the Shift-click should be removed when `silent_reset` is selected. (The confirmation for the Reset in the drop-down should stay at it is.)

– Tom

**Comment by tflo** [comment]
PS:

A simple hack does it for me:

Core.lua, line 159:
``` lua
function ldb:OnClick(button)
	if button == "LeftButton" then
		if IsShiftKeyDown() then
			if C.silent_reset then
				addon:Reset()
			else
				StaticPopup_Show("RESET_DATA")
			end
		else
			addon:ToggleVisibility()
		end
	elseif addon.windows.title_hide then
		addon:DropdownMenu()
	end
end
```

This is for when `silent_reset` is set. I haven’t tried to make it for other cases, as I always have `silent_reset` on.

**Comment by tflo** [comment]
Heck, is there any setting that tells Github that one tab == 2 spaces ? Or maybe 4, but not freakin 8!! (In fenced codeblocks, I mean.)

**Comment by Wetxius** [comment]
https://github.com/Wetxius/Numeration/commit/2999c392c93ddc4279c3255d7610939122e70080

**Comment by tflo** [comment]
Great, thanks!
